name: Brave Pet Academy
favicon: null
layout_spectrum: 0.75734
typography_spectrum: 0.82081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0094d1'
    - '#ffffff'
    - '#5ed0e7'
    - '#abf1fd'
    - '#006991'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.8338828701525927
  rhythmicContrast: 0.25
purpose: []
